<?php
$severityOrder = ['critical' => 0, 'high' => 1, 'medium' => 2, 'low' => 3];
$findings = collect($check->findings)->sortBy(fn ($f) => $severityOrder[$f['severity']] ?? 4)->values();
$severityLabels = ['critical' => 'Critical', 'high' => 'High', 'medium' => 'Medium', 'low' => 'Low'];
$severityColors = ['critical' => '#B91C1C', 'high' => '#C2410C', 'medium' => '#A16207', 'low' => '#475569'];
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Helvetica, Arial, sans-serif; color: #0F172A; font-size: 11px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  h2 { font-size: 14px; margin: 22px 0 10px; }
  .muted { color: #64748B; }
  table.meta { width: 100%; margin-bottom: 16px; border-collapse: collapse; }
  table.meta td { padding: 3px 0; }
  table.meta td.label { color: #64748B; width: 140px; }
  .score-banner { background: #F1F5F9; border-radius: 6px; padding: 14px 16px; margin-bottom: 16px; }
  .score-banner .big { font-size: 30px; font-weight: bold; }
  table.engines { width: 100%; border-collapse: collapse; margin-bottom: 4px; }
  table.engines th, table.engines td { border: 1px solid #CBD5E1; padding: 6px 8px; text-align: left; font-size: 10px; }
  table.engines th { background: #F1F5F9; }
  .finding { border: 1px solid #CBD5E1; border-radius: 4px; padding: 8px 10px; margin-bottom: 8px; }
  .finding .badge { display: inline-block; font-size: 8px; font-weight: bold; text-transform: uppercase; letter-spacing: .5px; padding: 2px 6px; border-radius: 3px; color: #fff; margin-bottom: 4px; }
  .finding .title { font-weight: bold; font-size: 11px; margin: 2px 0 4px; }
  .finding .detail { color: #334155; margin-bottom: 4px; }
  .finding .fix { color: #065F46; background: #ECFDF5; padding: 5px 7px; border-radius: 3px; }
  .footer-note { margin-top: 20px; color: #64748B; font-size: 9px; border-top: 1px solid #CBD5E1; padding-top: 10px; }
</style>
</head>
<body>
  <h1>INZRA — AI SEO Optimization Report</h1>
  <p class="muted">Full findings and fixes to move this page toward a 100% AI visibility score</p>

  <table class="meta">
    <tr><td class="label">Target URL</td><td>{{ $check->url }}</td></tr>
    <tr><td class="label">Report generated</td><td>{{ now()->format('j F Y, g:ia') }}</td></tr>
    <tr><td class="label">Issues found</td><td>{{ count($check->findings) }}</td></tr>
  </table>

  <div class="score-banner">
    <span class="big">{{ $check->overall_score }}</span><span class="muted">/100 overall AI visibility score</span>
  </div>

  <h2>Score by AI engine</h2>
  <table class="engines">
    <thead>
      <tr>
        <th>Engine</th>
        <th>Score</th>
        <th>Crawler access</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($check->engine_scores as $engine)
        <tr>
          <td>{{ $engine['name'] }}</td>
          <td>{{ $engine['score'] }}/100</td>
          <td>{{ $engine['crawler_allowed'] ? 'Allowed' : 'Blocked by robots.txt' }}</td>
        </tr>
      @endforeach
    </tbody>
  </table>

  <h2>Issues found, in priority order</h2>

  @forelse ($findings as $finding)
    <div class="finding">
      <span class="badge" style="background: {{ $severityColors[$finding['severity']] ?? '#475569' }};">{{ $severityLabels[$finding['severity']] ?? ucfirst($finding['severity']) }} priority</span>
      <p class="title">{{ $finding['title'] }}</p>
      <p class="detail">{{ $finding['detail'] }}</p>
      <p class="fix"><strong>Fix:</strong> {{ $finding['fix'] }}</p>
    </div>
  @empty
    <p class="muted">No issues found — this page already covers every signal in our audit.</p>
  @endforelse

  <p class="footer-note">Methodology: this report is a deterministic on-page audit of crawler access (robots.txt), structured data, content clarity, and authority/freshness signals, weighted per engine based on publicly documented crawling and citation behavior. It is not a live query sent to ChatGPT, Gemini, Perplexity, Claude or Copilot, and does not guarantee inclusion in any AI-generated answer. Generated by INZRA — inzra.com</p>
</body>
</html>
