<?php

/*
|--------------------------------------------------------------------------
| Legacy slug redirects
|--------------------------------------------------------------------------
|
| Product/blog URLs used to end in a 6-digit SKU (e.g. -443387). That was
| dropped for cleaner URLs; these carry real inbound-link SEO equity from
| before the change, so anyone who still has an old link gets sent to the
| renamed page rather than a 404. Preserved verbatim from the old
| .htaccess (legacy-static-reference/.htaccess, originally lines 105-184).
|
*/

return [
    'products/100-dofollow-backlinks-for-any-url-322520' => '/products/100-dofollow-backlinks-for-any-url',
    'blog/100-dofollow-backlinks-for-any-url-322520' => '/blog/100-dofollow-backlinks-for-any-url',
    'products/100-high-da-manual-backlinks-da-70-white-hat-seo-958325' => '/products/100-high-da-manual-backlinks-da-70-white-hat-seo',
    'blog/100-high-da-manual-backlinks-da-70-white-hat-seo-958325' => '/blog/100-high-da-manual-backlinks-da-70-white-hat-seo',
    'products/100-permanent-uk-backlinks-with-high-pr-sites-se-552405' => '/products/100-permanent-uk-backlinks-with-high-pr-sites',
    'blog/100-permanent-uk-backlinks-with-high-pr-sites-se-552405' => '/blog/100-permanent-uk-backlinks-with-high-pr-sites',
    'products/100-unique-domain-authority-seo-backlinks-on-hig-388396' => '/products/100-unique-domain-authority-seo-backlinks',
    'blog/100-unique-domain-authority-seo-backlinks-on-hig-388396' => '/blog/100-unique-domain-authority-seo-backlinks',
    'products/1000-google-authority-entity-stacking-permanent-531225' => '/products/1000-google-authority-entity-stacking-permanent',
    'blog/1000-google-authority-entity-stacking-permanent-531225' => '/blog/1000-google-authority-entity-stacking-permanent',
    'products/1000-high-quality-seo-contextual-backlinks-022592' => '/products/1000-high-quality-seo-contextual-backlinks',
    'blog/1000-high-quality-seo-contextual-backlinks-022592' => '/blog/1000-high-quality-seo-contextual-backlinks',
    'products/1000-high-quality-seo-contextual-backlinks-408223' => '/products/1000-high-quality-seo-contextual-backlinks-2',
    'blog/1000-high-quality-seo-contextual-backlinks-408223' => '/blog/1000-high-quality-seo-contextual-backlinks-2',
    'products/1000-mexico-spanish-seo-backlinks-388222' => '/products/1000-mexico-spanish-seo-backlinks',
    'blog/1000-mexico-spanish-seo-backlinks-388222' => '/blog/1000-mexico-spanish-seo-backlinks',
    'products/300-whitehat-highest-quality-contextual-dofollow-068635' => '/products/300-whitehat-highest-quality-contextual-dofollow',
    'blog/300-whitehat-highest-quality-contextual-dofollow-068635' => '/blog/300-whitehat-highest-quality-contextual-dofollow',
    'products/3000-keyword-target-high-quality-do-follow-backl-391337' => '/products/3000-keyword-target-high-quality-do-follow-backlinks',
    'blog/3000-keyword-target-high-quality-do-follow-backl-391337' => '/blog/3000-keyword-target-high-quality-do-follow-backlinks',
    'products/3600-google-map-point-seo-backlinks-200-web-2-0-394951' => '/products/3600-google-map-point-seo-backlinks-200-web-2-0',
    'blog/3600-google-map-point-seo-backlinks-200-web-2-0-394951' => '/blog/3600-google-map-point-seo-backlinks-200-web-2-0',
    'products/50-da50-pbn-backlinks-of-the-highest-quality-918228' => '/products/50-da50-pbn-backlinks-of-the-highest-quality',
    'blog/50-da50-pbn-backlinks-of-the-highest-quality-918228' => '/blog/50-da50-pbn-backlinks-of-the-highest-quality',
    'products/500-backlinks-mexicanos-web-2-0-seo-linkbuilding-691832' => '/products/500-backlinks-mexicanos-web-2-0-seo-linkbuilding',
    'blog/500-backlinks-mexicanos-web-2-0-seo-linkbuilding-691832' => '/blog/500-backlinks-mexicanos-web-2-0-seo-linkbuilding',
    'products/500-deutsche-backlinks-backlinks-kaufen-seo-link-686207' => '/products/500-deutsche-backlinks-backlinks-kaufen-seo-link',
    'blog/500-deutsche-backlinks-backlinks-kaufen-seo-link-686207' => '/blog/500-deutsche-backlinks-backlinks-kaufen-seo-link',
    'products/500-high-quality-seo-article-backlinks-285885' => '/products/500-high-quality-seo-article-backlinks',
    'blog/500-high-quality-seo-article-backlinks-285885' => '/blog/500-high-quality-seo-article-backlinks',
    'products/500-homepage-pbn-seo-backlinks-all-dofollow-high-768732' => '/products/500-homepage-pbn-seo-backlinks-all-dofollow-high',
    'blog/500-homepage-pbn-seo-backlinks-all-dofollow-high-768732' => '/blog/500-homepage-pbn-seo-backlinks-all-dofollow-high',
    'products/500-sitemap-indexing-seo-backlinks-043482' => '/products/500-sitemap-indexing-seo-backlinks',
    'blog/500-sitemap-indexing-seo-backlinks-043482' => '/blog/500-sitemap-indexing-seo-backlinks',
    'products/500-web-2-0-backlinks-keyword-optimierte-backlin-072342' => '/products/500-web-2-0-backlinks-keyword-optimierte-backlinks',
    'blog/500-web-2-0-backlinks-keyword-optimierte-backlin-072342' => '/blog/500-web-2-0-backlinks-keyword-optimierte-backlinks',
    'products/500-yt-seo-backlniks-video-embedded-seo-backlink-038993' => '/products/500-yt-seo-backlniks-video-embedded-seo-backlink',
    'blog/500-yt-seo-backlniks-video-embedded-seo-backlink-038993' => '/blog/500-yt-seo-backlniks-video-embedded-seo-backlink',
    'products/5000-permanent-dofollow-verified-backlinks-top-a-889592' => '/products/5000-permanent-dofollow-verified-backlinks-top',
    'blog/5000-permanent-dofollow-verified-backlinks-top-a-889592' => '/blog/5000-permanent-dofollow-verified-backlinks-top',
    'products/6000-seo-backlinks-5000-dofollow-contextual-web2-088639' => '/products/6000-seo-backlinks-5000-dofollow-contextual-web2',
    'blog/6000-seo-backlinks-5000-dofollow-contextual-web2-088639' => '/blog/6000-seo-backlinks-5000-dofollow-contextual-web2',
    'products/80-german-backlinks-dofollow-by-top-level-domain-151843' => '/products/80-german-backlinks-dofollow-by-top-level-domain',
    'blog/80-german-backlinks-dofollow-by-top-level-domain-151843' => '/blog/80-german-backlinks-dofollow-by-top-level-domain',
    'products/ai-ranker-5000-premium-faq-backlinks-to-rank-in-642503' => '/products/ai-ranker-5000-premium-faq-backlinks-to-rank-in',
    'blog/ai-ranker-5000-premium-faq-backlinks-to-rank-in-642503' => '/blog/ai-ranker-5000-premium-faq-backlinks-to-rank-in',
    'products/boost-your-seo-ranking-with-golden-1000-backlink-941504' => '/products/boost-your-seo-ranking-with-golden-1000-backlink',
    'blog/boost-your-seo-ranking-with-golden-1000-backlink-941504' => '/blog/boost-your-seo-ranking-with-golden-1000-backlink',
    'products/boost-your-website-ranking-with-1000-high-da-dof-513052' => '/products/boost-your-website-ranking-with-1000-high-da-dofollow',
    'blog/boost-your-website-ranking-with-1000-high-da-dof-513052' => '/blog/boost-your-website-ranking-with-1000-high-da-dofollow',
    'products/complete-seo-pack-backlinks-from-22-platforms-so-417745' => '/products/complete-seo-pack-backlinks-from-22-platforms',
    'blog/complete-seo-pack-backlinks-from-22-platforms-so-417745' => '/blog/complete-seo-pack-backlinks-from-22-platforms',
    'products/da-80-seo-backlink-dofollow-backlink-link-buildi-920955' => '/products/da-80-seo-backlink-dofollow-backlink-link-building',
    'blog/da-80-seo-backlink-dofollow-backlink-link-buildi-920955' => '/blog/da-80-seo-backlink-dofollow-backlink-link-building',
    'products/da-90-high-authority-backlinks-boost-your-seo-fa-629293' => '/products/da-90-high-authority-backlinks-boost-your-seo-fast',
    'blog/da-90-high-authority-backlinks-boost-your-seo-fa-629293' => '/blog/da-90-high-authority-backlinks-boost-your-seo-fast',
    'products/domain-website-submission-to-320-search-engines-441301' => '/products/domain-website-submission-to-320-search-engines',
    'blog/domain-website-submission-to-320-search-engines-441301' => '/blog/domain-website-submission-to-320-search-engines',
    'products/google-maps-for-local-seo-premium-promtion-packa-053529' => '/products/google-maps-for-local-seo-premium-promtion-package',
    'blog/google-maps-for-local-seo-premium-promtion-packa-053529' => '/blog/google-maps-for-local-seo-premium-promtion-package',
    'products/high-quality-anchor-text-backlinks-seo-boost-wit-406205' => '/products/high-quality-anchor-text-backlinks-seo-boost-with',
    'blog/high-quality-anchor-text-backlinks-seo-boost-wit-406205' => '/blog/high-quality-anchor-text-backlinks-seo-boost-with',
    'products/online-shoping-websites-seo-5000-backlinks-e-com-102691' => '/products/online-shoping-websites-seo-5000-backlinks-e-commerce',
    'blog/online-shoping-websites-seo-5000-backlinks-e-com-102691' => '/blog/online-shoping-websites-seo-5000-backlinks-e-commerce',
    'products/premium-custom-website-design-development-modern-162598' => '/products/premium-custom-website-design-development-modern',
    'blog/premium-custom-website-design-development-modern-162598' => '/blog/premium-custom-website-design-development-modern',
    'products/premium-package-100-usa-backlinks-high-domain-au-460958' => '/products/premium-package-100-usa-backlinks-high-domain',
    'blog/premium-package-100-usa-backlinks-high-domain-au-460958' => '/blog/premium-package-100-usa-backlinks-high-domain',
    'products/premium-svenska-backlinks-500-h-gkvalitativa-l-n-064053' => '/products/premium-svenska-backlinks-500-hogkvalitativa-lankar',
    'blog/premium-svenska-backlinks-500-h-gkvalitativa-l-n-064053' => '/blog/premium-svenska-backlinks-500-hogkvalitativa-lankar',
    'products/premium-website-seo-backlink-power-pack-443387' => '/products/premium-website-seo-backlink-power-pack',
    'blog/premium-website-seo-backlink-power-pack-443387' => '/blog/premium-website-seo-backlink-power-pack',
    'products/rank-10-keywords-on-google-s-first-page-with-inz-180018' => '/products/rank-10-keywords-on-google-s-first-page-with-inzra',
    'blog/rank-10-keywords-on-google-s-first-page-with-inz-180018' => '/blog/rank-10-keywords-on-google-s-first-page-with-inzra',
    'products/skyrocket-your-seo-with-google-stacking-backlink-546926' => '/products/skyrocket-your-seo-with-google-stacking-backlink',
    'blog/skyrocket-your-seo-with-google-stacking-backlink-546926' => '/blog/skyrocket-your-seo-with-google-stacking-backlink',
    'products/web-2-0-contextual-backlinks-for-any-url-344843' => '/products/web-2-0-contextual-backlinks-for-any-url',
    'blog/web-2-0-contextual-backlinks-for-any-url-344843' => '/blog/web-2-0-contextual-backlinks-for-any-url',
    'products/youtube-video-seo-ranking-1000-backlinks-video-e-950492' => '/products/youtube-video-seo-ranking-1000-backlinks-video',
    'blog/youtube-video-seo-ranking-1000-backlinks-video-e-950492' => '/blog/youtube-video-seo-ranking-1000-backlinks-video',
];
